USE ROLE ACCOUNTADMIN;
USE WAREHOUSE PJM_WH;
USE DATABASE PJM_MARKET_DB;
USE SCHEMA ANALYTICS;

CREATE OR REPLACE TABLE RAW_AEP_LOAD_HOURLY (
    DATETIME_BEGINNING_UTC TIMESTAMP_NTZ,
    DATETIME_BEGINNING_EPT TIMESTAMP_NTZ,
    NERC_REGION STRING,
    MKT_REGION STRING,
    ZONE STRING,
    LOAD_AREA STRING,
    MW FLOAT,
    IS_VERIFIED BOOLEAN
);

CREATE OR REPLACE TABLE RAW_WEATHER_HOURLY (
    TIME TIMESTAMP_NTZ,
    TEMPERATURE_2M FLOAT
);

CREATE OR REPLACE TABLE RAW_LMP_HOURLY (
    DATETIME_BEGINNING_UTC TIMESTAMP_NTZ,
    DATETIME_BEGINNING_EPT TIMESTAMP_NTZ,
    PNODE_ID NUMBER,
    PNODE_NAME STRING,
    VOLTAGE STRING,
    EQUIPMENT STRING,
    TYPE STRING,
    ZONE STRING,
    SYSTEM_ENERGY_PRICE_RT FLOAT,
    TOTAL_LMP_RT FLOAT,
    CONGESTION_PRICE_RT FLOAT,
    MARGINAL_LOSS_PRICE_RT FLOAT,
    SYSTEM_ENERGY_PRICE_DA FLOAT,
    TOTAL_LMP_DA FLOAT,
    CONGESTION_PRICE_DA FLOAT,
    MARGINAL_LOSS_PRICE_DA FLOAT
);
