USE ROLE ACCOUNTADMIN;
USE WAREHOUSE PJM_WH;
USE DATABASE PJM_MARKET_DB;
USE SCHEMA ANALYTICS;

CREATE OR REPLACE TABLE MART_AEP_MARKET_HOURLY AS
WITH load_hourly AS (
    SELECT
        DATETIME_BEGINNING_EPT AS DATETIME,
        SUM(MW) AS LOAD_MW
    FROM RAW_AEP_LOAD_HOURLY
    WHERE DATETIME_BEGINNING_EPT IS NOT NULL
    GROUP BY DATETIME_BEGINNING_EPT
),
weather_hourly AS (
    SELECT
        TIME AS DATETIME,
        TEMPERATURE_2M
    FROM RAW_WEATHER_HOURLY
    WHERE TIME IS NOT NULL
),
lmp_clean AS (
    SELECT
        DATETIME_BEGINNING_EPT AS DATETIME,
        TOTAL_LMP_DA AS TOTAL_LMP_DAY_AHEAD,
        TOTAL_LMP_RT AS TOTAL_LMP_REAL_TIME,
        CONGESTION_PRICE_DA AS CONGESTION_PRICE_DAY_AHEAD,
        CONGESTION_PRICE_RT AS CONGESTION_PRICE_REAL_TIME,
        MARGINAL_LOSS_PRICE_DA AS MARGINAL_LOSS_PRICE_DAY_AHEAD,
        MARGINAL_LOSS_PRICE_RT AS MARGINAL_LOSS_PRICE_REAL_TIME
    FROM RAW_LMP_HOURLY
    WHERE DATETIME_BEGINNING_EPT IS NOT NULL
),
lmp_features AS (
    SELECT
        *,
        TOTAL_LMP_REAL_TIME - TOTAL_LMP_DAY_AHEAD AS RT_DA_SPREAD,
        CONGESTION_PRICE_DAY_AHEAD / NULLIF(TOTAL_LMP_DAY_AHEAD, 0) AS CONGESTION_SHARE_DA,
        CONGESTION_PRICE_REAL_TIME / NULLIF(TOTAL_LMP_REAL_TIME, 0) AS CONGESTION_SHARE_RT,
        IFF(
            TOTAL_LMP_DAY_AHEAD > PERCENTILE_CONT(0.95) WITHIN GROUP (ORDER BY TOTAL_LMP_DAY_AHEAD) OVER (),
            1,
            0
        ) AS DA_PRICE_SPIKE,
        IFF(
            TOTAL_LMP_REAL_TIME > PERCENTILE_CONT(0.95) WITHIN GROUP (ORDER BY TOTAL_LMP_REAL_TIME) OVER (),
            1,
            0
        ) AS RT_PRICE_SPIKE
    FROM lmp_clean
),
joined AS (
    SELECT
        l.DATETIME,
        l.TOTAL_LMP_DAY_AHEAD,
        l.TOTAL_LMP_REAL_TIME,
        l.CONGESTION_PRICE_DAY_AHEAD,
        l.CONGESTION_PRICE_REAL_TIME,
        l.MARGINAL_LOSS_PRICE_DAY_AHEAD,
        l.MARGINAL_LOSS_PRICE_REAL_TIME,
        l.RT_DA_SPREAD,
        l.CONGESTION_SHARE_DA,
        l.CONGESTION_SHARE_RT,
        l.DA_PRICE_SPIKE,
        l.RT_PRICE_SPIKE,
        load.LOAD_MW,
        w.TEMPERATURE_2M
    FROM lmp_features l
    INNER JOIN load_hourly load
        ON l.DATETIME = load.DATETIME
    INNER JOIN weather_hourly w
        ON l.DATETIME = w.DATETIME
)
SELECT
    DATETIME,
    TOTAL_LMP_DAY_AHEAD,
    TOTAL_LMP_REAL_TIME,
    CONGESTION_PRICE_DAY_AHEAD,
    CONGESTION_PRICE_REAL_TIME,
    MARGINAL_LOSS_PRICE_DAY_AHEAD,
    MARGINAL_LOSS_PRICE_REAL_TIME,
    RT_DA_SPREAD,
    CONGESTION_SHARE_DA,
    CONGESTION_SHARE_RT,
    DA_PRICE_SPIKE,
    RT_PRICE_SPIKE,
    LOAD_MW,
    TEMPERATURE_2M,
    DATE_PART('HOUR', DATETIME) AS HOUR,
    DAYOFWEEKISO(DATETIME) - 1 AS DAYOFWEEK,
    DATE_PART('MONTH', DATETIME) AS MONTH,
    IFF(DAYOFWEEKISO(DATETIME) IN (6, 7), 1, 0) AS IS_WEEKEND,
    SIN(2 * PI() * DATE_PART('HOUR', DATETIME) / 24) AS SIN_HOUR,
    COS(2 * PI() * DATE_PART('HOUR', DATETIME) / 24) AS COS_HOUR
FROM joined
ORDER BY DATETIME;
